remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Noel Toivio's Game Development Portfolio
description: A showcase of my work as a game designer.